# Netlify configuration for USDT NOW React/Vite app
[build]
  command = "npm run build"
  publish = "dist"
  ignore = "false"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "true"

# SPA redirects - CRITICAL for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Asset redirects to prevent 404s
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://app-misty-dream-49704848.dpl.myneon.app https://api.stack-auth.com https://api.ipify.org https://api.trongrid.io https://tronscan.org https://check.torproject.org; frame-ancestors 'none';"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# No cache for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# JavaScript files
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# CSS files
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"
